# .github/workflows/static.yml
name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust if needed

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        run: npm run build
        # Ensure your build output goes to the directory below

      - name: Upload Artifact for Deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: './build'  # Change this if your output directory is different

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Download Artifact
        uses: actions/download-pages-artifact@v1
        with:
          path: './build'

      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v1

